// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiqjWker1Xt1ZMKUrmTBqTL65jVsWEq2s',
    appId: '1:502715405212:web:27933e86372976eaeaee59',
    messagingSenderId: '502715405212',
    projectId: 'f-44-oua',
    authDomain: 'f-44-oua.firebaseapp.com',
    storageBucket: 'f-44-oua.appspot.com',
    measurementId: 'G-TC0VGC0KWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy7pSxbPgYNFcF6eQlPTzmmiJETPMaLoU',
    appId: '1:502715405212:android:3b52267df78a1836eaee59',
    messagingSenderId: '502715405212',
    projectId: 'f-44-oua',
    storageBucket: 'f-44-oua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkUkglz_raQRg37Tm6ilvJHH0KLhJHZLk',
    appId: '1:502715405212:ios:bed129daf4ca5e4eeaee59',
    messagingSenderId: '502715405212',
    projectId: 'f-44-oua',
    storageBucket: 'f-44-oua.appspot.com',
    iosClientId: '502715405212-4tnk0jn8ecne6e9uuhon625hkkgq4gm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.f44Oua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkUkglz_raQRg37Tm6ilvJHH0KLhJHZLk',
    appId: '1:502715405212:ios:bed129daf4ca5e4eeaee59',
    messagingSenderId: '502715405212',
    projectId: 'f-44-oua',
    storageBucket: 'f-44-oua.appspot.com',
    iosClientId: '502715405212-4tnk0jn8ecne6e9uuhon625hkkgq4gm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.f44Oua',
  );
}
